Eshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import  static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('store.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path , include
from . import views
from .middleware.auth import auth_middleware
urlpatterns = [
         
    path('', views.Index.as_view(), name='index'),
    path('signup', views.Signup , name='signup'),
    path('login', views.Login.as_view() , name='login'),
    path('logout', views.logout , name='logout'),
    path('cart', auth_middleware(views.cart) , name='cart'),


    path('checkout', views.checkout , name='checkout'),
    path('showorderconfirm', views.showorderconfirm , name='showorderconfirm'),
    
    # path('orders', views.orders , name='orders'),
    path('male', views.Malecatageory.as_view() , name='male'),
    path('female', views.Femalecatageory.as_view() , name='female'),
    path('kid', views.Kidcatageory.as_view() , name='kid'),
   
    path('todo', views.todo, name='todo'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('change/<int:id>', views.change, name='change'),
    path('check-email', views.check_email, name='check_email'),
    path('sendingemail', views.sendingemail, name='sendingemail'),
    path('infoemailsend', views.infoemailsend, name='infoemailsend'),
    path('resetpassform/<int:id>', views.resetpassform, name='resetpassform'),
    path('customerprofile', views.customerprofile, name='customerprofile'),
    path('profileeditpage', views.profileeditpage , name='profileeditpage'),
    path('addreview' , views.addreview , name='addreview'),
    path('profiledeletepage', views.profiledeletepage , name='profiledeletepage'),
    path('search', views.search , name='search'),
    path('<int:product_id>' , views.productdetail , name='productdetail'),
    path('filterproducts' , views.filterproducts , name='filterproducts'),
    path('addtocart', views.addtocart , name='addtocart'),
    path('deletefromcart' , views.deletefromcart , name='deletefromcart'),
    path('updatecartqty' , views.updatecartqty , name='updatecartqty'),
    path('shop' , views.shop , name='shop'),
    path('base', views.base , name='base'),


    path('dashboard', views.dashboard , name='dashboard'),
    path('cartorder', views.cartorder , name='cartorder'),
    path('my_order_items/<int:id>',views.my_order_items,name='my_order_items'),
    path('cancelorder' , views.cancelorder , name='cancelorder'),
    path('reviewspage' , views.reviewspage , name='reviewspage'),
    path('contact',views.contact , name='contact')
 ]

store/models.py
from django.db import models
import datetime
from datetime import timedelta
from django.utils import timezone

class Category(models.Model):
    name=models.CharField(max_length=50)
    
    def __str__(self):
        return str(self.name)
    
class Color(models.Model):
    title=models.CharField(max_length=50)
    color_code=models.CharField(max_length=50)
    
    def __str__(self):
        return str(self.title)
    
class Size(models.Model):
    title=models.CharField(max_length=50)
    
    def __str__(self):
        return str(self.title)    

class Products(models.Model):
    name=models.CharField(max_length=50)
    price=models.DecimalField(max_digits=6, decimal_places=2)
    description=models.TextField()
    category=models.ForeignKey(Category , on_delete=models.CASCADE)
    image=models.ImageField(upload_to='uploadedimages/')

    def __str__(self):
        return str(self.name)

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url
    


    @staticmethod
    def get_all_products_by_id(category_id):
        if category_id:
            return Products.objects.filter(category=category_id)
        else:
            return Products.objects.all()

    @staticmethod
    def det_product_by_id(ids):
        return Products.objects.filter(id__in=ids)
       
		
class ProductAttribute(models.Model):
    product=models.ForeignKey(Products, on_delete=models.CASCADE)
    color=models.ForeignKey(Color, on_delete=models.CASCADE)
    size=models.ForeignKey(Size, on_delete=models.CASCADE)
    price=models.DecimalField(max_digits=6, decimal_places=2)
    # image=models.ImageField(upload_to='uploadedimages/' ,blank=True, null=True)


    def __str__(self):
        return str(self.product.name)

        
class Customer(models.Model):
    first_name=models.CharField(max_length=50)
    last_name=models.CharField(max_length=50)
    phone=models.CharField(max_length=11)
    email=models.EmailField()
    password=models.CharField(max_length=600)

    def __str__(self):
        return str(self.first_name)	

    
    def register(self):
        self.save()	



    def isExist(self):
        return Customer.objects.filter(email=self.email).exists()   



    @staticmethod
    def get_customer_by_email(email):
        try:
            return Customer.objects.get(email=email)
        except:
            return False    
        


# Order
status_choice=(
        ('process','In Process'),
        ('shipped','Shipped'),
        ('delivered','Delivered'),
        ('canceled', 'Canceled')
    )
class CartOrder(models.Model):
    customer=models.ForeignKey(Customer,on_delete=models.CASCADE)
    total_price = models.IntegerField(blank=True, null=True)
    paid_status=models.BooleanField(default=False)
    date=models.DateField(default=datetime.datetime.today)
    order_status=models.CharField(choices=status_choice,default='process',max_length=150)

    def __str__(self):
        return str(self.customer)	
    
      # Check if the order can be canceled (within 24 hours and status is 'process')
    @property
    def can_cancel(self):
        cancel_time_limit = timedelta(hours=24)  # Time limit for order cancellation (24 hours)
        return timezone.now().date() <= (self.date + cancel_time_limit) and self.order_status == 'process'


	
class Order(models.Model):
    order=models.ForeignKey(CartOrder,on_delete=models.CASCADE , null=True)
    product=models.ForeignKey(Products, on_delete=models.CASCADE)
    customer=models.ForeignKey(Customer, on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)
    price=models.IntegerField()
    adress=models.CharField(max_length=500 , default="")
    phone=models.CharField( max_length=50, default="")
    color = models.CharField(max_length=30, blank=True, null=True)
    size = models.CharField(max_length=30, blank=True, null=True)
    total_price = models.IntegerField(blank=True, null=True)
    status=models.BooleanField(default=False)

    date=models.DateField(default=datetime.datetime.today)


    def __str__(self):
        return str(self.customer)
    

    def place_order(self):
        return self.save()
    
    @staticmethod
    def get_orders(customer_id):
        return Order.objects.filter(customer = customer_id).order_by('-date')


class Profile(models.Model):
    customer=models.ForeignKey(Customer, on_delete=models.CASCADE)
    cover_photo=models.ImageField(upload_to='uploadedimages/')
    profile_photo=models.ImageField(upload_to='uploadedimages/')
    address = models.CharField(max_length=255, blank=True, null=True)
    about = models.CharField(max_length=500,blank=True, null=True)

    def __str__(self):
        return str(self.customer)


class Todo(models.Model):
    customer=models.ForeignKey(Customer, on_delete=models.CASCADE)
    title=models.CharField(max_length=500 , default="")
    description=models.CharField(max_length=500 , default="")
    status=models.BooleanField(default=False)
    date=models.DateField(default=datetime.datetime.today)



    def __str__(self):
        return str(self.customer)
    

    @staticmethod
    def get_todos(customer_id):
        return Todo.objects.filter(customer = customer_id).order_by('-date')
    


class Reviews(models.Model):
    customer=models.ForeignKey(Customer, on_delete=models.CASCADE)
    product=models.ForeignKey(Products, on_delete=models.CASCADE)
    title=models.CharField(max_length=800 , default="")
    stars = models.IntegerField(blank=True, null=True)
    date=models.DateField(default=datetime.datetime.today)

    def __str__(self):
        return str(self.customer)

store/templates/cartorder.html
{% extends "base.html" %}
{% block title %}
<title>Orders</title>


<style>
    .text-center2{
        text-align:center;
        margin-bottom:20px;
    }

    .text-center3{
        text-align:center;
        margin-bottom:20px;
        width: 200px;
    }
    .cardanker{
        text-decoration: none;
        color: black;
    }
    .cardanker:hover{
        color:black;
    }

    .footeroscarddata{
        text-align:center;
    }    
    .canceled-text {
        text-decoration: line-through;
        
    }
    
</style>

{% endblock %}

{% block content %}

<!-- Custom CSS for Dashboard -->


{% include "dashboarduper.html" %}

        <!-- Dashboard Content Section -->
        <div class="col-lg-9">
            <div class="row">
                {% for item in orders_with_items %}
                <div class="col-md-12  ">
                    <div class="card cart-item {% if item.order.order_status == 'canceled' %}canceled-text{% endif %}" id="order-card-{{ item.order.id }}">
                        <a class="cardanker canceltext " href="my_order_items/{{item.order.id}}">
                        <div class="card-body bodyofcard">
                            <div class="row">
                                <h3 class="text-center2">Order No #{{ forloop.counter }}</h3>

                                <div class="col-md-4 col-6 "> <!-- Use col-md-6 for desktop and col-12 for mobile -->
                                    <div class="cart-item-details">
                                        <h5><strong>Order Total:</strong><br> <span class='text-danger'>${{ item.order.total_price }} {{item.order.id}}</span></h5>
                                    </div>
                                    
                                    <input type="hidden" id="cartorderid-{{ item.order.id }}" value="{{ item.order.id }}">
                                </div>
                                <div class="col-md-4 col-6"> <!-- Use col-md-6 for desktop and col-12 for mobile -->
                                    
                                    <div class="cart-item-details">
                                        <h5><strong>Order Items:</strong> <span class='text-danger'>{{item.item_count}}</span></h5>
                                    </div>
                                    <p class='mt-1'><strong>Date:</strong> {{ item.order.date }}</p>

                                </div>
                             
                                <div class="col-md-4 col-12"> <!-- Same here for responsive design -->
                                    <p><strong>Status:</strong> {{ item.order.get_order_status_display }}</p>
                                    <p><strong>Paid: </strong> 
                                        {% if item.order.paid_status %}
                                        Paid
                                        {% else %}
                                        Unpaid
                                        {% endif %}
                                    </p>
                                </div>
                            </div>
                            <div class='footeroscarddata'>
                            <button class="text-center3 btn ">More Details</button>
                            {% if item.order.order_status == 'canceled' %}
                            {% else %}
                            {% if item.order.can_cancel %}
                            <p>you will cancel your order in 24 hours after placing order:<a class='cancel-order-btn' href="">cancel Order</a></p>
                            {% endif %}
                            {% endif %}
                            

                        </div>
                        </div>
                    </a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
   
{% include "dashboardlower.html" %}


<script>
    $('.cancel-order-btn').on('click', function (e) {
        e.preventDefault();  // Prevent the default behavior of the link
    
        var orderId = $(this).closest('.card').find('input[type="hidden"]').val();
        var cardId = '#order-card-' + orderId;
        console.log(orderId);
        
        // Confirm cancellation
        if (confirm('Are you sure you want to cancel this order?')) {
            $.ajax({
                url: "{% url 'cancelorder' %}",
                data: {
                    'order_id': orderId,
                },
                success: function (response) {
                    if (response.status === 'success') {
                        // Update the card to show it as canceled
                        $(cardId).find('.row').addClass('canceled-text');
                        $(cardId).find('.cancel-order-btn').remove();
                        alert(response.message);  // Success message
                    } else {
                        alert(response.message);  // Error message
                    }
                },
                error: function (xhr, status, error) {
                    alert('An error occurred while processing your request.');
                }
            });
        }
    });
</script>
{% endblock %}

store/templates/dashboard.html
{% extends "base.html" %}
{% load static %}
{% block title %}
<title>Dashboard</title>


{% endblock %}

{% block content %}

<!-- Custom CSS for Dashboard -->


{% include "dashboarduper.html" %}

        <!-- Dashboard Content Section -->
        <div class="col-lg-9">
            <div class="row">
                <div class="container">
                    <h2 class="text-center">Shopping Overview</h2>
                    <canvas id="orderChart" width="400" height="200"></canvas>
                </div>
            </div>
        </div>
   
{% include "dashboardlower.html" %}

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    var ctx = document.getElementById('orderChart').getContext('2d');
    var orderChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: {{ labels|safe }},  // Date labels
            datasets: [{
                label: 'Number of Orders',
                data: {{ data|safe }},  // Order counts
                backgroundColor: 'rgba(75, 192, 192, 0.6)',
                borderColor: 'rgba(75, 192, 192, 1)',
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
    });
</script>
{% endblock %}

store/templates/dashboardlower.html
</div>
</div>

<!-- Filter Sidebar for Mobile (Hidden by default) -->
<div class="filter-sidebar-mobile d-lg-none">
    <div class="close-sidebar">X</div>
    <div class="filter-content">
        <div class="list-group list-group-flush imagesidebar">
            <img src="{{ profile.first.profile_photo.url }}" alt="Profile Picture">
            <a href="{% url 'profileeditpage' %}"><i class="fas fa-camera"></i></a>
            <h3>{{customer.first_name}}</h3>
        </div>
        <div class="list-group list-group-flush">
            <a href="{% url 'dashboard' %}" class="list-group-item list-group-item-action mt-2">Dashboard</a>
            <a href="{% url 'customerprofile' %}" class="list-group-item list-group-item-action mt-2">Profile</a>
            <a href="{% url 'cartorder' %}" class="list-group-item list-group-item-action mt-2">Orders</a>
            <a href="{% url 'reviewspage' %}" class="list-group-item list-group-item-action mt-2">Reviews</a>
            <a href="{% url 'todo' %}" class="list-group-item list-group-item-action mt-2">TODOS</a>
            <a href="{% url 'logout' %}" class="list-group-item list-group-item-action mt-2">Logout</a>

        </div>
    </div>
</div>

<script>
    // Mobile filter toggle
    document.getElementById("toggleFilters").addEventListener("click", function() {
        document.querySelector(".filter-sidebar-mobile").classList.toggle("active");
    });

    // Close mobile sidebar
    document.querySelector(".close-sidebar").addEventListener("click", function() {
        document.querySelector(".filter-sidebar-mobile").classList.remove("active");
    });
</script>

store/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>Store - Home</title>

<!-- Swiper CSS -->
<link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">

<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-6VD8YPr2e6DWoWvHwZefbPqFYPLb67jmwzPDBkegT2vlH/wnZBL9HjggK7tBTZx" crossorigin="anonymous">

{% endblock %}

{% block content %}

<!-- Slider Section (Bootstrap Carousel) -->
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'images/slide1.jpg' %}" class="d-block w-100" alt="Slide 1">
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/slide2.jpg' %}" class="d-block w-100" alt="Slide 2">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

<!-- Collection List Section -->
<div class="container my-5">
  <h2 class="text-center mb-4">Our Collections</h2>
  <div class="row">
    <div class="col-md-4">
      <div class="card">
        <a href="{% url 'male' %}"><img src="{% static 'images/male-category.jpg' %}" class="card-img-top" alt="Male Watches">
        <div class="card-body text-center"></a>
          <h5 class="card-title">Male Watches</h5>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card">
        <a href="{% url 'female' %}"><img src="{% static 'images/female-category.jpg' %}" class="card-img-top" alt="Female Watches">
        <div class="card-body text-center"></a>
          <h5 class="card-title">Female Watches</h5>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card">
        <a href="{% url 'kid' %}"><img src="{% static 'images/kids-category.jpg' %}" class="card-img-top" alt="Kids Watches">
        <div class="card-body text-center"></a>
          <h5 class="card-title">Kids Watches</h5>
        </div>
      </div>
    </div>
  </div>
</div>


<!-- Swiper Section males -->
<div class="container my-5">
  <h2 class="text-center mb-4">Weekly Deal Foe Males</h2>
  <div class="swiper mySwiper">
    <div class="swiper-wrapper">
      {% for items in male %}
      <div class="swiper-slide">
        <div class="card product-card h-100 shadow-sm rounded">
          <a href="{% url 'productdetail' items.id %}" class="card-img-container">
            <img src="{{ items.imageURL }}" class="card-img-top" alt="{{ items.name }}">
          </a>
          <div class="card-body">
            <h5 class="card-title text-truncate">{{ items.name }}</h5>
            <p class="card-text text-muted">$ {{ items.productattribute_set.first.price }}</p>
          </div>
          <div class="card-footer d-flex justify-content-between align-items-center">

            <input type="hidden" class="productid-{{ items.id }}"  value="{{ items.id }}" >
            <input type="hidden" class="productcolor-{{ items.id }}" value="{{items.productattribute_set.first.color.id}}">
            <input type="hidden" class="producttitle-{{ items.id }}" value="{{items.name}}">
            <input type="hidden" class="productprice-{{ items.id }}" value="{{items.productattribute_set.first.price}}">
            <input type="hidden" class="productquantity-{{ items.id }}" value="1">
            <input type="hidden" class="productsize-{{ items.id }}" value="{{items.productattribute_set.first.size}}">

            <button type="button" data-address='{{ items.id }}'  class="btn-light  cart-btn btn-sm addtofirstcart">
              <i class="fas fa-shopping-cart"></i>
          </button>
            <a href="{% url 'productdetail' items.id %}" class="btn btn-outline-dark buy-now-btn">Buy Now</a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <!-- Add Pagination and Navigation Buttons -->
    <div class="swiper-pagination"></div>
    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
  </div>
</div>




<!-- Swiper Section  females -->
<div class="container my-5 pt-5">
  <h2 class="text-center mb-4">Weekly Deal For Females</h2>
  <div class="swiper mySwiper">
    <div class="swiper-wrapper">
      {% for items in female %}
      <div class="swiper-slide">
        <div class="card product-card h-100 shadow-sm rounded">
          <a href="{% url 'productdetail' items.id %}" class="card-img-container">
            <img src="{{ items.imageURL }}" class="card-img-top" alt="{{ items.name }}">
          </a>
          <div class="card-body">
            <h5 class="card-title text-truncate">{{ items.name }}</h5>
            <p class="card-text text-muted">$ {{ items.productattribute_set.first.price }}</p>
          </div>
          <div class="card-footer d-flex justify-content-between align-items-center">

            <input type="hidden" class="productid-{{ items.id }}"  value="{{ items.id }}" >
            <input type="hidden" class="productcolor-{{ items.id }}" value="{{items.productattribute_set.first.color.id}}">
            <input type="hidden" class="producttitle-{{ items.id }}" value="{{items.name}}">
            <input type="hidden" class="productprice-{{ items.id }}" value="{{items.productattribute_set.first.price}}">
            <input type="hidden" class="productquantity-{{ items.id }}" value="1">
            <input type="hidden" class="productsize-{{ items.id }}" value="{{items.productattribute_set.first.size}}">

            <button type="button" data-address='{{ items.id }}'  class="btn-light  cart-btn btn-sm addtofirstcart">
              <i class="fas fa-shopping-cart"></i>
          </button>
            <a href="{% url 'productdetail' items.id %}" class="btn btn-outline-dark buy-now-btn">Buy Now</a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <!-- Add Pagination and Navigation Buttons -->
    <div class="swiper-pagination"></div>
    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
  </div>
</div>



<!-- Swiper Section  females -->
<div class="container my-5 pt-5">
  <h2 class="text-center mb-4">Weekly Deal For Females</h2>
  <div class="swiper mySwiper">
    <div class="swiper-wrapper">
      {% for items in kid %}
      <div class="swiper-slide">
        <div class="card product-card h-100 shadow-sm rounded">
          <a href="{% url 'productdetail' items.id %}" class="card-img-container">
            <img src="{{ items.imageURL }}" class="card-img-top" alt="{{ items.name }}">
          </a>
          <div class="card-body">
            <h5 class="card-title text-truncate">{{ items.name }}</h5>
            <p class="card-text text-muted">$ {{ items.productattribute_set.first.price }}</p>
          </div>
          <div class="card-footer d-flex justify-content-between align-items-center">

            <input type="hidden" class="productid-{{ items.id }}"  value="{{ items.id }}" >
            <input type="hidden" class="productcolor-{{ items.id }}" value="{{items.productattribute_set.first.color.id}}">
            <input type="hidden" class="producttitle-{{ items.id }}" value="{{items.name}}">
            <input type="hidden" class="productprice-{{ items.id }}" value="{{items.productattribute_set.first.price}}">
            <input type="hidden" class="productquantity-{{ items.id }}" value="1">
            <input type="hidden" class="productsize-{{ items.id }}" value="{{items.productattribute_set.first.size}}">

            <button type="button" data-address='{{ items.id }}'  class="  cart-btn btn-sm addtofirstcart">
              <i class="fas fa-shopping-cart"></i>
          </button>
            <a href="{% url 'productdetail' items.id %}" class="btn btn-outline-dark buy-now-btn">Buy Now</a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <!-- Add Pagination and Navigation Buttons -->
    <div class="swiper-pagination"></div>
    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
  </div>
</div>




<!-- jQuery -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<!-- Swiper JS -->
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>

<!-- Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-mQ93sKBIwmEaXr2toJ5poHHM+M8pQuB0Ifw8zQJwEyz43GK5nwh3dBzRPw6l0HUY" crossorigin="anonymous"></script>

<!-- Swiper Initialization -->
<script>
  var swiper = new Swiper(".mySwiper", {
    slidesPerView: 1,
    spaceBetween: 10,
    loop: true,
    navigation: {
      nextEl: ".swiper-button-next",
      prevEl: ".swiper-button-prev",
    },
    breakpoints: {
      500: {
        slidesPerView: 2,
        spaceBetween: 10,
      },
      1000: {
        slidesPerView: 4,
        spaceBetween: 30,
      }
    }
  });
</script>



{% endblock %}

store/templates/orders.html
{% extends "base.html" %}

{% load cart %}

{% block title %}
<title>Order Details</title>

<style>
    .canceled-text {
        text-decoration: line-through;
        border:1px solid red;
        
    }
</style>
{% endblock %}

{% block content %}
{% include "dashboarduper.html" %}

<!-- Order Details Section -->
<div class="col-lg-9">
    <div class="container mt-5">
        <h2 class="text-center mb-4">Your Order Details</h2>
        <div class="row justify-content-center">
            <!-- Order and Shipping Information -->
            <div class="col-12 mb-4 ">
                <div class="card p-3 shadow-sm {% if order.order_status == 'canceled' %}canceled-text{% endif %} ">
                    <h4 class="mb-3">Shipping Information</h4>
                    <p><strong>Name:</strong> {{ order.customer.first_name }}</p>
                    <p><strong>Email:</strong> {{ order.customer.email }}</p>
                    <p><strong>Phone:</strong> {{ order.customer.phone }}</p>
                    <p><strong>Address:</strong> {{ orderitems.first.adress }}</p>
                    <p><strong>Order Date:</strong> {{ order.date }}</p>
                    <p><strong>Status:</strong> 
                        
                        {{ order.get_order_status_display }}
                    </p>
                </div>
            </div>

            <!-- Product Details Section -->
            {% for item in orderitems %}
            <div class="col-12 mb-4">
                <div class="card p-3 shadow-sm">
                    <div class="row">
                        <div class="col-md-3">
                            <img src="{{ item.product.imageURL }}" alt="{{ item.product.name }}" class="img-fluid rounded">
                        </div>
                        <div class="col-md-9">
                            <h5 class="card-title"><strong>{{ item.product.name }}</strong></h5>
                            <p class="mb-1"><strong>Price:</strong> ${{ item.price }}</p>
                            <p class="mb-1"><strong>Quantity:</strong> {{ item.quantity }}</p>
                            <p class="mb-1"><strong>Size:</strong> {{ item.size }}</p>
                            <p class="mb-1"><strong>Color:</strong> {{ item.color }}</p>
                            <p class="mb-1"><strong>Total Price:</strong> ${{ item.total_price }}</p>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% include "dashboardlower.html" %}
{% endblock %}

store/templates/search.html
{% extends "base.html" %}
{% block title %}
<title>Search Result</title>
{% endblock %} 

{% load cart %}

{% block content %}

<!-- Banner Section -->
<div class="banner-section banner text-center py-5" style="">
    <h1>Search Results</h1>
    <p>Home/Search</p>
</div>

<div class="container mt-5">
    <div class="row">
        <div class="col">
            <div class="row mx-auto">
               
                {% for items in search_result %}
                <div class="col-6 col-md-4 col-lg-3 mb-4">
                    <div class="card product-card h-100 shadow-sm rounded">
                        <a href="{% url 'productdetail' items.id %}" class="card-img-container">
                            <img src="{{items.imageURL}}" class="card-img-top" alt="{{items.name}}">
                        </a>
                        <div class="card-body">
                            <h5 class="card-title text-truncate">{{items.name}}</h5>
                            <p class="card-text text-muted" >$ {{items.productattribute_set.first.price}}</p>
                        </div>
                        <div class="card-footer d-flex justify-content-between align-items-center">
                                <input type="hidden" class="productid-{{ items.id }}"  value="{{ items.id }}" >
                                <input type="hidden" class="productcolor-{{ items.id }}" value="{{items.productattribute_set.first.color.id}}">
                                <input type="hidden" class="producttitle-{{ items.id }}" value="{{items.name}}">
                                <input type="hidden" class="productprice-{{ items.id }}" value="{{items.productattribute_set.first.price}}">
                                <input type="hidden" class="productquantity-{{ items.id }}" value="1">
                                <input type="hidden" class="productsize-{{ items.id }}" value="{{items.productattribute_set.first.size}}">

                                
                                <button type="button" data-address='{{ items.id }}'  class="btn btn-light cart-btn btn-sm addtofirstcart">
                                    <i class="fas fa-shopping-cart"></i>
                                </button>
                                
                                <a type="button" href="{% url 'productdetail' items.id %}" class="btn btn-outline-dark buy-now-btn">
                                    Buy Now
                                </a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}